Repository test-organization-kkjeer/rubengu-test, pull requests merged in 2020-05, with the labels that each got.

#28 add vs
  manifests/Microsoft/VisualStudio/Community/16.0.30011.22.yaml
Labels: AzurePipelinePassed, ValidationCompleted, auto merge

#29 add fake
  manifests/Microsoft/PowerToys/0.15.3.yaml
Labels: auto merge

#19 Sublime test
  manifests/Sublime/Sublime/0.73.yaml
Labels: AzurePipelinePassed

#30 Teams test
  manifests/Microsoft/Teams/1.3.yaml
Labels: Azure-Pipeline-Passed

#34 delete
  manifests/7Zip/7Zip/16.0.4.yaml
Labels: Azure-Pipeline-Passed

#36 BeyondCompare4
  manifests/ScooterSoftware/BeyondCompare4/4.3.4.24657.yaml
Labels: Azure-Pipeline-Passed

#37 whats
  manifests/whatsapp/WhatsApp/2.2019.8.yaml
Labels: Azure-Pipeline-Passed

#38 powertoy
  manifests/Microsoft/PowerToys/0.17.0.yaml
Labels: Azure-Pipeline-Passed
